const API_URL="";const P={BULANAN:["Laporan Bulanan","📅"],TRIWULAN:["Laporan Triwulan","📈"],SEMESTER:["Laporan Semester","📚"],TAHUNAN:["Laporan Tahunan","📊"],LAINNYA:["Laporan Lainnya","📁"]};let years=[2026],data=[],year=2026,period="BULANAN";
addEventListener("DOMContentLoaded",init);
async function init(){if(API_URL){try{let r=await api("getData");years=r.years||[2026];data=r.data||[]}catch(e){msg("Gagal mengambil database")}}else load();year=years.includes(2026)?2026:years[0];render()}
function setPeriodView(p){period=p;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.period==p));render()}
function render(){years.sort((a,b)=>a-b);let ys=document.getElementById("yearSelect");ys.innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join("");ys.value=year;document.getElementById("mYear").innerHTML=years.map(y=>`<option>${y}</option>`).join("");document.getElementById("mYear").value=year;document.getElementById("periodYear").textContent=year;document.getElementById("periodLabel").textContent=P[period][0].replace("Laporan ","");
let q=document.getElementById("search").value.toLowerCase(),rows=data.filter(x=>+x.tahun==year&&x.periode==period&&(!q||String(x.nama).toLowerCase().includes(q)));let all=data.filter(x=>+x.tahun==year),done=all.filter(x=>x.status=="SUDAH DIISI").length;let progress=all.length?Math.round(all.reduce((s,x)=>s+(+x.progress||x.status=="SUDAH DIISI"?100:0),0)/all.length):0;
document.getElementById("overall").textContent=progress+"%";document.getElementById("total").textContent=rows.length;document.getElementById("fileCount").textContent=rows.filter(x=>x.link).length;document.getElementById("done100").textContent=all.filter(x=>(+x.progress||0)>=100||x.status=="SUDAH DIISI").length;
let groups={};all.forEach(x=>{groups[x.periode]=(groups[x.periode]||[]).concat(x)});let arr=Object.entries(groups);document.getElementById("progressRows").innerHTML=arr.length?arr.map(([k,a])=>{let avg=Math.round(a.reduce((s,x)=>s+(+x.progress||x.status=="SUDAH DIISI"?100:0),0)/a.length);return`<div class="progress-item"><div class="progress-meta"><div class="work-name">${P[k]?.[0]||k}<small>${a.length} laporan · ${a.filter(x=>x.link).length} file</small></div><div class="bar"><i style="width:${avg}%"></i></div><div class="work-percent">${avg}%</div></div></div>`}).join(""):`<div class="progress-item">Belum ada data laporan.</div>`;
document.getElementById("categoryCards").innerHTML=arr.map(([k,a])=>{let avg=Math.round(a.reduce((s,x)=>s+(+x.progress||x.status=="SUDAH DIISI"?100:0),0)/a.length);return`<div class="category-card" onclick="setPeriodView('${k}')"><div class="donut" style="--p:${avg}"><span>${avg}%</span></div><div><h4>${P[k]?.[0]||k}</h4><small>${a.length} laporan · ${a.filter(x=>x.link).length} file</small></div></div>`}).join("");
document.getElementById("detail").classList.remove("show");if(period)detail(rows)}
function selectYear(y){year=y;render()}
function detail(rows){document.getElementById("detailTitle").textContent=P[period][0];document.getElementById("detailSub").textContent=rows.length+" laporan pada tahun "+year;document.getElementById("menus").innerHTML=rows.length?rows.map(x=>`<div class="menu"><h4>${esc(x.nama)}</h4><a href="${esc(x.link)}" target="_blank">🔗 ${esc(x.link)}</a><span class="status ${x.status=="SUDAH DIISI"?"done":"todo"}">${x.status} · ${+x.progress||0}%</span><br><button onclick="toggle('${x.id}')">${x.status=="SUDAH DIISI"?"Tandai Belum":"Tandai Sudah"}</button><button onclick="del('${x.id}')">Hapus</button></div>`).join(""):`<div class="menu"><h4>Belum ada submenu</h4><p>Tambahkan laporan menggunakan tombol Tambah.</p></div>`}
function openMenu(){document.getElementById("mPeriod").value=period;document.getElementById("menuModal").classList.add("show")}function closeMenu(){document.getElementById("menuModal").classList.remove("show");document.getElementById("mName").value="";document.getElementById("mLink").value=""}
async function saveMenu(){let x={id:crypto.randomUUID(),tahun:+document.getElementById("mYear").value,periode:document.getElementById("mPeriod").value,nama:document.getElementById("mName").value.trim(),link:document.getElementById("mLink").value.trim(),status:document.getElementById("mStatus").value,progress:+document.getElementById("mProgress").value||0};if(!x.nama||!x.link)return msg("Nama dan link wajib diisi");if(x.status=="SUDAH DIISI")x.progress=100;if(API_URL)await api("addMenu",x);data.push(x);year=x.tahun;period=x.periode;closeMenu();render();msg("Laporan berhasil ditambahkan")}
async function toggle(id){let x=data.find(a=>a.id==id);x.status=x.status=="SUDAH DIISI"?"BELUM DIISI":"SUDAH DIISI";x.progress=x.status=="SUDAH DIISI"?100:0;if(API_URL)await api("updateStatus",{id,status:x.status,progress:x.progress});render();msg("Status diperbarui")}
async function del(id){if(!confirm("Hapus laporan ini?"))return;if(API_URL)await api("deleteMenu",{id});data=data.filter(x=>x.id!=id);render();msg("Laporan dihapus")}
function openYear(){document.getElementById("yearModal").classList.add("show")}function closeYear(){document.getElementById("yearModal").classList.remove("show")}async function saveYear(){let y=+document.getElementById("newYear").value;if(!y||years.includes(y))return msg("Tahun tidak valid atau sudah ada");if(API_URL)await api("addYear",{tahun:y});years.push(y);year=y;closeYear();render();msg("Tahun "+y+" ditambahkan")}
function api(action,p={}){return new Promise((ok,no)=>{let c="cb"+Date.now();window[c]=r=>{delete window[c];s.remove();r.ok?ok(r):no(r)};let s=document.createElement("script");s.src=API_URL+"?action="+action+"&callback="+c+"&"+new URLSearchParams(p);s.onerror=no;document.body.appendChild(s)})}
function load(){try{data=JSON.parse(localStorage.getItem("laporanData")||"[]");years=JSON.parse(localStorage.getItem("laporanYears")||"[2026]")}catch(e){}}addEventListener("beforeunload",()=>{if(!API_URL){localStorage.setItem("laporanData",JSON.stringify(data));localStorage.setItem("laporanYears",JSON.stringify(years))}});
function msg(t){let e=document.getElementById("toast");e.textContent=t;e.style.display="block";setTimeout(()=>e.style.display="none",2200)}function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}